# Aprende más sobre la configuración en https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "76290212e01f7e4535a9e3413a2002da"
name = "ProAlert — Product Warnings"
application_url = "https://example.com"
embedded = true

[access_scopes]
scopes = "read_products"

[auth]
redirect_urls = [ "https://example.com/auth/callback" ]

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = ["app/uninstalled"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = ["app/scopes_update"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = ["customers/data_request"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = ["customers/redact"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = ["shop/redact"]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
